stages:
  - build

variables:
  SPECNAME: harbour-dool.spec
  YAMLNAME: harbour-dool.yaml
  SRCREPO: "https://github.com/scottchiefbaker/dool/"
  USE_COMMIT: "yes"
  COMMIT: 6b89f2d0b6e38e1c8d706e88a12e020367f5100d

include:
  - 'https://gitlab.com/nephros/ci-templates/-/raw/master/sfos/sfos-build-git-remote.yml'

build:
  stage: build
  extends: .build-bin
  variables:
    TARGET: "armv7hl"

.build-local:
  image:
      name: "sailfishos-platform-sdk:latest"
      entrypoint: [""]
  artifacts:
    when: always
    paths:
      - "output/*.log"
      - "output/*"
  script:
    #- SRCVER=v$(awk -F ":" '/Version/ {print $2}' rpm/$YAMLNAME | xargs echo)
    - git clone --depth 5 $SRCURI ~/build
    - cp -av rpm ~/build
    #- cp -av files/* ~/build/rpm/
    - export OUTDIR=$CI_PROJECT_DIR/output
    - pushd ~/build
    - git checkout $SRCVER
    - specify --non-interactive --skip-scm --not-download -o rpm/$SPECNAME rpm/$YAMLNAME
    - |
      for SFOS_VERSION in $SFOS_VERSIONS; do
        mkdir -p $OUTDIR/$SFOS_VERSION
        echo "~~~ VERSION $SFOS_VERSION ~~~"
        for TARGET in $TARGETS; do
          echo "~~~ TARGET $TARGET ~~~"
          mb2 -t SailfishOS-$SFOS_VERSION-$TARGET -s rpm/$SPECNAME prepare | tee -a $OUTDIR/$SFOS_VERSION-$TARGET-prepare.log
          cp -rv ~/build/rpm/*.spec $OUTDIR/
          mb2 -t SailfishOS-$SFOS_VERSION-$TARGET -s rpm/$SPECNAME build --enable-debug | tee -a $OUTDIR/$SFOS_VERSION-$TARGET-build.log
          cp -rv ~/build/RPMS/* $OUTDIR/$SFOS_VERSION
        done
      done
    - popd

