# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-dool

# >> macros
# << macros

Summary:    Pluggable real-time performance monitoring tool
Version:    0.9.10
Release:    1
Group:      Applications/System
License:    GPL
BuildArch:  noarch
URL:        https://github.com/scottchiefbaker/dool/
Source0:    https://github.com/scottchiefbaker/dool/archive/02b1c69d441764b030db5e78b4b6fb231c29f8f1.tar.gz
Source100:  harbour-dool.yaml
Patch0:     PR1.patch
Patch1:     PR2.patch
Requires:   python >= 2.6
Requires:   python-six
BuildRequires:  python >= 2.6
Provides:   dstat
Obsoletes:   dstat <= 0.7.2
Obsoletes:   harbour-dstat <= %{version}

%description
Dool is a Python3 compatible clone of Dstat.
After Dag Wieers ceased development of Dstat scottchiefbaker forked the
project to continue development. Dool is a Python 2.x and 3.x compatible
version of Dstat with a couple minor bug fixes.

The Description for original dstat follows:

Dstat is a versatile replacement for vmstat, iostat, netstat and ifstat.
Dstat overcomes some of their limitations and adds some extra features,
more counters and flexibility. Dstat is handy for monitoring systems
during performance tuning tests, benchmarks or troubleshooting.

Dstat allows you to view all of your system resources in real-time, you
can eg. compare disk utilization in combination with interrupts from your
IDE controller, or compare the network bandwidth numbers directly
with the disk throughput (in the same interval).

Dstat gives you detailed selective information in columns and clearly
indicates in what magnitude and unit the output is displayed. Less
confusion, less mistakes. And most importantly, it makes it very easy
to write plugins to collect your own counters and extend in ways you
never expected.


%prep
%setup -q -n %{name}-%{version}

# PR1.patch
%patch0 -p1
# PR2.patch
%patch1 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
sed -i -e "s@/usr/share/dool/@%{_datadir}/%{name}/plugins/@" dool
install -Dp -m0755 dool %{buildroot}/%{_bindir}/dool
install -d  -m0755 %{buildroot}/%{_datadir}/dool/
install -Dp -m0755 dool %{buildroot}/%{_datadir}/%{name}/dool.py
install -d  -m0755 %{buildroot}/%{_datadir}/%{name}/plugins/
install -Dp -m0644 plugins/dool_*.py %{buildroot}/%{_datadir}/%{name}/plugins/
# << install pre

# >> install post
pushd %{buildroot}/%{_bindir}
ln -s dool dstat
popd
# << install post

%files
%defattr(-,root,root,-)
%license COPYING
%{_bindir}/dool
%{_bindir}/dstat
%{_datadir}/%{name}/
# >> files
# << files
